export default {
  PREPARATION: [
    'Dem Bundesrat zugeleitet - Noch nicht beraten',
    'Dem Bundestag zugeleitet - Noch nicht beraten',
    'Den Ausschüssen zugewiesen',
    'Einbringung abgelehnt',
    '1. Durchgang im Bundesrat abgeschlossen',
    'Überwiesen',
    'Noch nicht beraten',
    'Keine parlamentarische Behandlung',
    'Nicht abgeschlossen - Einzelheiten siehe Vorgangsablauf',
  ],
  VOTING: ['Beschlussempfehlung liegt vor'],
  COMPLETED: [
    'Erledigt durch Ablauf der Wahlperiode',
    'Zurückgezogen',
    'Angenommen',
    'Abgelehnt',
    'Abgeschlossen - Ergebnis siehe Vorgangsablauf',
    'Für nichtig erklärt',
    'Verkündet',
    'Zusammengeführt mit... (siehe Vorgangsablauf)',
    'Für erledigt erklärt',
    'Verabschiedet',
    'Bundesrat hat zugestimmt',
    'Bundesrat hat Einspruch eingelegt',
    'Bundesrat hat Zustimmung versagt',
    'Bundesrat hat Vermittlungsausschuss nicht angerufen',
    'Im Vermittlungsverfahren',
    'Vermittlungsvorschlag liegt vor',
    'Für mit dem Grundgesetz unvereinbar erklärt',
    'Nicht ausgefertigt wegen Zustimmungsverweigerung des Bundespräsidenten',
    'Zustimmung versagt',
    'Teile des Gesetzes für nichtig erklärt',
    'Für gegenstandslos erklärt',
    'Einbringung abgelehnt',
  ],
};
